scan_timeout = 60
add_newline = false 

[line_break]
disabled = false 

[cmd_duration]
format = "[$duration]($style) "

[git_branch]
format = "[$symbol$branch]($style) "

[package]
format = "[$symbol$version]($style) "
symbol = " "

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"

[php]
format = "[$symbol($version )]($style)"
symbol = " "

[java]
format = "[${symbol}(${version} )]($style)"
symbol = " "

[rust]
format = "[$symbol($version )]($style)"

[golang]
format = "[$symbol($version )]($style)"
symbol = " "
